2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:313) *** Starting import-mailbox-to-gmail 1.6 on Python 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.3)] ***
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:317) Arguments:
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:319) 	dir: '/Users/rt/import-mailbox-to-gmail/mbox_directory'
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:319) 	fix_msgid: True
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:319) 	from_message: 0
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:319) 	json: 'key.json'
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:319) 	log: 'import-mailbox-to-gmail-70633.log'
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:319) 	logging_level: 'INFO'
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:319) 	num_retries: 10
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:319) 	replace_quoted_printable: True
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:321) Checking directory: /Users/rt/import-mailbox-to-gmail/mbox_directory
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:322) Directory exists: True
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:323) Is directory: True
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:327) Directory contents: ['.DS_Store', 'ryan@ryantaylor.me']
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:333) Subdirectories: ['ryan@ryantaylor.me']
2024-10-15T09:45:40 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:350) Processing user ryan@ryantaylor.me
2024-10-15T09:45:40 (-0400) 70633 INFO autodetect (__init__.py:49) file_cache is only supported with oauth2client<4.0.0
2024-10-15T09:45:41 (-0400) 70633 ERROR main (import-mailbox-to-gmail.py:364) Can't get labels for user ryan@ryantaylor.me
2024-10-15T09:45:41 (-0400) 70633 ERROR main (import-mailbox-to-gmail.py:393) Can't process user ryan@ryantaylor.me
Traceback (most recent call last):
  File "/Users/rt/import-mailbox-to-gmail/import-mailbox-to-gmail.py", line 361, in main
    fields='labels(id,name)').execute(num_retries=args.num_retries)
                              ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rt/import-mailbox-to-gmail/myenv/lib/python3.13/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/rt/import-mailbox-to-gmail/myenv/lib/python3.13/site-packages/googleapiclient/http.py", line 923, in execute
    resp, content = _retry_request(
                    ~~~~~~~~~~~~~~^
        http,
        ^^^^^
    ...<7 lines>...
        headers=self.headers,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/rt/import-mailbox-to-gmail/myenv/lib/python3.13/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
                    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rt/import-mailbox-to-gmail/myenv/lib/python3.13/site-packages/google_auth_httplib2.py", line 209, in request
    self.credentials.before_request(self._request, method, uri, request_headers)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rt/import-mailbox-to-gmail/myenv/lib/python3.13/site-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/rt/import-mailbox-to-gmail/myenv/lib/python3.13/site-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
    ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/rt/import-mailbox-to-gmail/myenv/lib/python3.13/site-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ~~~~~~~~~~~~~~~~~^
        request, self._token_uri, assertion
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/rt/import-mailbox-to-gmail/myenv/lib/python3.13/site-packages/google/oauth2/_client.py", line 298, in jwt_grant
    response_data = _token_endpoint_request(
        request,
    ...<5 lines>...
        },
    )
  File "/Users/rt/import-mailbox-to-gmail/myenv/lib/python3.13/site-packages/google/oauth2/_client.py", line 269, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rt/import-mailbox-to-gmail/myenv/lib/python3.13/site-packages/google/oauth2/_client.py", line 68, in _handle_error_response
    raise exceptions.RefreshError(
        error_details, response_data, retryable=retryable_error
    )
google.auth.exceptions.RefreshError: ('unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.', {'error': 'unauthorized_client', 'error_description': 'Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.'})
2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:394) *** Done importing all users from directory '/Users/rt/import-mailbox-to-gmail/mbox_directory'
2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:395) *** Import summary:
2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:396)     0 users imported with no failures
2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:398)     0 users imported with some failures
2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:400)     1 users failed
2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:402)     0 labels (mbox files) imported with no failures
2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:404)     0 labels (mbox files) imported with some failures
2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:406)     0 labels (mbox files) failed
2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:408)     0 messages imported successfully
2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:410)     0 messages failed

2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:414) *** Check log file import-mailbox-to-gmail-70633.log for detailed errors.
2024-10-15T09:45:41 (-0400) 70633 INFO main (import-mailbox-to-gmail.py:415) Finished.


